# Generated by Django 3.1.2 on 2020-10-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boast_roast',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
